In [10]:
import pandas as pd

df = pd.read_csv("./../data/urls_features.csv")

print("Liczba rekordów:", df.shape[0])
print("Liczba kolumn:", df.shape[1])

print("\nInformacje o kolumnach:")
df.info()
TARGET = "type"

Liczba rekordów: 641013
Liczba kolumn: 33

Informacje o kolumnach:
<class 'pandas.DataFrame'>
RangeIndex: 641013 entries, 0 to 641012
Data columns (total 33 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   url                       641013 non-null  str
 1   type                      641013 non-null  str
 2   domain                    628882 non-null  str
 3   tld                       628881 non-null  str
 4   suffix                    628881 non-null  str
 5   subdomain                 250634 non-null  str
 6   url_length                641013 non-null  int64
 7   domain_length             641013 non-null  int64
 8   subdomain_length          641013 non-null  int64
 9   suffix_length             641013 non-null  int64
 10  host_length               641013 non-null  int64
 11  path_length               641013 non-null  int64
 12  arguments_url_ratio       641013 non-null  float64
 13  path_url_ratio            641013 non-null  float64
 14  arguments_domain_ratio    641013 non-null  float64
 15  arguments_hostname_ratio  641013 non-null  float64
 16  subdomain_domain_ratio    641013 non-null  float64
 17  suffix_tld_ratio          641013 non-null  float64
 18  longest_url_token_length  641013 non-null  int64
 19  average_url_token_length  641013 non-null  float64
 20  dot_count                 641013 non-null  int64
 21  hyphen_count              641013 non-null  int64
 22  underscore_count          641013 non-null  int64
 23  question_mark_count       641013 non-null  int64
 24  equal_sign_count          641013 non-null  int64
 25  ampersand_count           641013 non-null  int64
 26  has_https                 641013 non-null  int64
 27  domain_entropy            641013 non-null  float64
 28  subdomain_entropy         641013 non-null  float64
 29  symbol_count              641013 non-null  int64
 30  digit_count               641013 non-null  int64
 31  is_ip                     641013 non-null  int64
 32  label                     641013 non-null  int64
dtypes: float64(9), int64(18), str(6)
memory usage: 161.4 MB

In [14]:
df_train = pd.read_csv("./../data/train.csv")
df_val = pd.read_csv("./../data/validation.csv")
df_test = pd.read_csv("./../data/test.csv")

class_counts = pd.DataFrame({
    "Original": df["type"].value_counts(),
    "Train": df_train["type"].value_counts(),
    "Validation": df_val["type"].value_counts(),
    "Test": df_test["type"].value_counts()
})

display(class_counts)

class_distribution = pd.DataFrame({
    "Original": df["type"].value_counts(normalize=True),
    "Train": df_train["type"].value_counts(normalize=True),
    "Validation": df_val["type"].value_counts(normalize=True),
    "Test": df_test["type"].value_counts(normalize=True)
}) * 100

display(class_distribution.round(2))

            Original   Train  Validation   Test
type
benign        428181  299727       64227  64227
defacement     95308   66716       14296  14296
phishing       93879   65715       14082  14082
malware        23645   16551        3547   3547

            Original  Train  Validation   Test
type
benign         66.80  66.80       66.80  66.80
defacement     14.87  14.87       14.87  14.87
phishing       14.65  14.65       14.65  14.65
malware         3.69   3.69        3.69   3.69